package com.francesca.frattini.gymwebsite.entities;

public enum Allenamenti {

    PERSONAL_TRAINING,
    ALLENAMENTO_DI_GRUPPO,
    PREPARAZ_ATLETICA_PALLAVOLO,
    PREPARAZ_ATLETICA_BASKET,
    RIEDUCAZIONE_FUNZIONALE,
    RIATLETIZZAZ_POST_INFORTUNIO,
    ANALISI_BIOMECCANICA_CICLISTI,
    GINNASTICA_IN_GRAVIDANZA,
    GINNASTICA_POSTURALE_INDIVIDUALE,
    GINNASTICA_ADULTI,
    GINNASTICA_TERZA_ETA,
    OSTEOPATIA_ADULTI,
    OSTEOPATIA_GRAVIDANZA,
    OSTEOPATIA_PEDIATRICA,
}
